version: "3.9"

services:
  app:
    build:
      context: .
      args:
        - DEV=true
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    command: >
      sh -c "flake8 && 
             python manage.py test && 
             python manage.py wait_for_db && 
             python manage.py migrate && 
             python manage.py runserver 0.0.0.0:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=imagedb
      - DB_USER=imageuser
      - DB_PASS=changeme
    depends_on:
      - db

  db:
    image: postgres:13-alpine
    volumes:
      - image-db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=imagedb
      - POSTGRES_USER=imageuser
      - POSTGRES_PASSWORD=changeme

volumes:
  image-db-data: