# Generated by Django 4.2.5 on 2023-09-25 00:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 25, 4, 16, 44, 933930, tzinfo=datetime.timezone.utc)),
        ),
    ]
