# Generated by Django 4.2.5 on 2023-09-25 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_picture_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='picture',
            name='expires_at',
            field=models.DateTimeField(),
        ),
    ]
