# Generated by Django 4.2.5 on 2023-09-26 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_picture_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='picture',
            name='link',
        ),
    ]
